In [1]:
import numpy as np

In [2]:
streetlights = np.array( [ [ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ],
 [ 0, 1, 1 ],
 [ 1, 0, 1 ] ] )

walk_vs_stop = np.array( [ [ 0 ],
 [ 1 ],
 [ 0 ],
 [ 1 ],
 [ 1 ],
 [ 0 ] ] )

weights = np.array([ 0.5, 0.7, 1.2 ])

def neural_network(inputs,weights):
    pred = inputs.dot(weights)
    return pred

alpha = 0.1
# for i in range(20):
#     pred = np.array(neural_network(streetlights,weights))
#     error = (pred - walk_vs_stop)**2
#     delta = pred - np.array(walk_vs_stop.T[0])
#     weighted_delta = delta.dot(streetlights)
#     weights = weighted_delta*alpha
#     print("Error:" + str(error) + " Prediction:" + str(pred))

input = streetlights[0] 
goal_prediction = walk_vs_stop[0]
for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]

        prediction = input.dot(weights)

        error = (goal_prediction - prediction)**2
        error_for_all_lights += error

        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print("Prediction:" + str(prediction))
    print("Errorfor iteration "+ str(iteration+1) + " - " + str(error_for_all_lights) + "\n")

Prediction:1.7
Prediction:1.73
Prediction:0.9570000000000001
Prediction:1.8183
Prediction:1.32464
Prediction:0.9951760000000001
Errorfor iteration 1 - [6.10413029]

Prediction:0.7961408
Prediction:1.08058032
Prediction:0.559816288
Prediction:1.0775209471999998
Prediction:0.9929784377599999
Prediction:0.558070945984
Errorfor iteration 2 - [1.27122962]

Prediction:0.4464567567872
Prediction:0.89392997993088
Prediction:0.406938952433792
Prediction:0.8352835437042048
Prediction:0.9073933799604837
Prediction:0.3692824654564035
Errorfor iteration 3 - [0.54825083]

Prediction:0.2954259723651228
Prediction:0.8594438601862344
Prediction:0.33956213502316795
Prediction:0.7644331314969774
Prediction:0.9007122483472751
Prediction:0.273482327237035
Errorfor iteration 4 - [0.36247737]

Prediction:0.21878586178962794
Prediction:0.8713429797751537
Prediction:0.30273026665624414
Prediction:0.7519654819524413
Prediction:0.9164082607640103
Prediction:0.2155874423216732
Errorfor iteration 5 - [0.27105214]


In [19]:
#Initializing the network’s weights and data
np.random.seed(1)
def relu(x):
    return (x > 0) * x 
    # return max(0,x)

def relu2deriv(output):
    return output>0    
     
lights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ] ] )

walk_stop = np.array([[ 1, 1, 0, 0]]).T
alpha = 0.2
hidden_size = 3
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

layer_0 = lights[0:1]
layer_1 = np.dot(layer_0,weights_0_1)
# layer_1 = np.dot(weights_0_1,layer_0) --> shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)
print(layer_1)
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1,weights_1_2)
error = (layer_2-walk_stop[0:1])**2
layer_2_delta=(layer_2-walk_stop[0:1])

layer_1, weights_0_1, layer_0

[[-0.79343557  0.13177044 -1.2062363 ]]


(array([[-0.        ,  0.13177044, -0.        ]]),
 array([[-0.16595599,  0.44064899, -0.99977125],
        [-0.39533485, -0.70648822, -0.81532281],
        [-0.62747958, -0.30887855, -0.20646505]]),
 array([[1, 0, 1]]))

In [17]:
layer_0

array([[1, 0, 1]])

In [11]:
weights_0_1

array([[-0.16595599,  0.44064899, -0.99977125],
       [-0.39533485, -0.70648822, -0.81532281],
       [-0.62747958, -0.30887855, -0.20646505]])

In [24]:
np.random.seed(1)
def relu(x):
 return (x > 0) * x 
def relu2deriv(output):
 return output>0 
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ] ] )
walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T
 
alpha = 0.2
hidden_size = 4
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1
for iteration in range(1):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
        layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
    if(iteration % 10 == 9):
        print("Error:" + str(layer_2_error))

In [25]:
# layer_2_delta.dot(weights_1_2.T)