In [1]:
import numpy as np

In [16]:
weight = 0.1
input = 0.5
goal = 0.9
alpha = 0.01
for i in range(20):
    pred = input * weight
    error = (pred - goal)** 2
    delta = (pred - goal)
    weighted_delta = delta*input
    weight = weight - weighted_delta*alpha
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.7224999999999999 Prediction:0.05
Error:0.718892015625 Prediction:0.052125000000000005
Error:0.7153020486219727 Prediction:0.054244687500000006
Error:0.7117300090166667 Prediction:0.056359075781250004
Error:0.7081758072841399 Prediction:0.05846817809179688
Error:0.7046393543465146 Prediction:0.06057200764656739
Error:0.7011205615707466 Prediction:0.06267057762745097
Error:0.6976193407664026 Prediction:0.06476390118338235
Error:0.6941356041834505 Prediction:0.06685199143042389
Error:0.6906692645100595 Prediction:0.06893486145184784
Error:0.6872202348704122 Prediction:0.07101252429821822
Error:0.6837884288225281 Prediction:0.07308499298747267
Error:0.6803737603560956 Prediction:0.075152280505004
Error:0.6769761438903175 Prediction:0.07721439980374149
Error:0.673595494271765 Prediction:0.07927136380423214
Error:0.6702317267722456 Prediction:0.08132318539472155
Error:0.6668847570866767 Prediction:0.08336987743123475
Error:0.6635545013309749 Prediction:0.08541145273765667
Error:0.660

In [9]:
weights = [0.1, 0.2, 0.3]  # Initial weights (one for each input)
inputs = [0.5, 1.0, 0.75]  # Multiple input values
goal = 0.9  # Target output
alpha = 0.01  # Learning rate
epochs = 20  # Number of iterations

for epoch in range(epochs):
    total_weighted_deltas = [0] * len(weights)  # Accumulate gradients for all weights

    # Compute gradients for each input
    for inp, weight in zip(inputs, weights):
        pred = sum(w * x for w, x in zip(weights, inputs))  # Compute prediction (linear combination)
        delta = (pred - goal)  # Error gradient
        weighted_delta = delta * inp  # Scale by input
        total_weighted_deltas = [tw + wd for tw, wd in zip(total_weighted_deltas, [weighted_delta] * len(weights))]

    # Update all weights using the average gradient
    weights = [w - (tw / len(inputs)) * alpha for w, tw in zip(weights, total_weighted_deltas)]

    # Compute new prediction and error after update
    pred = sum(w * x for w, x in zip(weights, inputs))
    error = (pred - goal) ** 2

    print(f"Epoch {epoch+1}: Error = {error:.5f}, Prediction = {pred:.5f}, Weights = {[round(w, 5) for w in weights]}")


Epoch 1: Error = 0.17458, Prediction = 0.48217, Weights = [0.10319, 0.20319, 0.30319]
Epoch 2: Error = 0.16874, Prediction = 0.48922, Weights = [0.10632, 0.20632, 0.30632]
Epoch 3: Error = 0.16309, Prediction = 0.49615, Weights = [0.1094, 0.2094, 0.3094]
Epoch 4: Error = 0.15763, Prediction = 0.50297, Weights = [0.11243, 0.21243, 0.31243]
Epoch 5: Error = 0.15236, Prediction = 0.50967, Weights = [0.11541, 0.21541, 0.31541]
Epoch 6: Error = 0.14726, Prediction = 0.51626, Weights = [0.11834, 0.21834, 0.31834]
Epoch 7: Error = 0.14233, Prediction = 0.52273, Weights = [0.12121, 0.22121, 0.32121]
Epoch 8: Error = 0.13757, Prediction = 0.52910, Weights = [0.12404, 0.22404, 0.32404]
Epoch 9: Error = 0.13296, Prediction = 0.53536, Weights = [0.12683, 0.22683, 0.32683]
Epoch 10: Error = 0.12851, Prediction = 0.54151, Weights = [0.12956, 0.22956, 0.32956]
Epoch 11: Error = 0.12421, Prediction = 0.54756, Weights = [0.13225, 0.23225, 0.33225]
Epoch 12: Error = 0.12006, Prediction = 0.55351, Weight

In [31]:
toes = [8.5 , 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2 , 1.3, 0.5, 1.0]
win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]
input = np.array([toes[0],wlrec[0],nfans[0]])
weights = np.array([0.1, 0.2, -.1]) 


def neural_network(input, weights):
    output = input.dot(weights)
    return output
# pred = neural_network(input,weights)
# pred
alpha = 0.01
for i in range(2):
    pred = neural_network(input,weights)
    error = (pred - true)**2
    delta = (pred - true)
    weighted_delta = delta*input
    weighted_delta[0] = 0 ## freezing one weight
    weights = weights - weighted_delta*alpha
    print(weighted_delta)
    print(weights)
    print("Error:" + str(error) + " Prediction:" + str(pred))

[ 0.    -0.091 -0.168]
[ 0.1      0.20091 -0.09832]
Error:0.01959999999999997 Prediction:0.8600000000000001
[ 0.         -0.08930512 -0.164871  ]
[ 0.1         0.20180305 -0.09667129]
Error:0.018876699056249977 Prediction:0.8626075000000001
