In [8]:
import pandas as pd
import numpy as np

In [9]:
# def neural_network(input,weight):
#     prediction = input*weight
#     return np.sum(prediction)

def neural_network(input,weights):
    prediction = input.dot(weights)
    return prediction

# number_of_toes = np.array([0.85,1.2,0.45])
# weights = np.array([0.1, 0.2, 0])
# predicted = neural_network(number_of_toes,weights)
# print(predicted)

weights = np.array([0.1, 0.2, 0])
toes = np.array([8.5, 9.5, 9.9, 9.0]) 
wlrec = np.array([0.65, 0.8, 0.8, 0.9]) 
nfans = np.array([1.2, 1.3, 0.5, 1.0]) 
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights) 
print(pred)

0.9800000000000001


In [10]:
def elementwise_multiplication(vec_a, vec_b):
    if len(vec_a) == len(vec_b):
        all = []
        for i in range(len(vec_a)):
            store = vec_a[i]*vec_b[i]
            all.append(store)
    return all

toes = [8.5, 9.5, 9.9, 9.0] 
wlrec = [0.65, 0.8, 0.8, 0.9] 
stored_mul = elementwise_multiplication(toes,wlrec)
print(stored_mul)

def elementwise_addition(vec_a, vec_b):
    if len(vec_a) == len(vec_b):
        all = []
        for i in range(len(vec_a)):
            store = vec_a[i]+vec_b[i]
            all.append(store)
    return all

stored_add = elementwise_addition(toes,wlrec)
print(stored_add)

def vector_sum(vec_a):
    output = 0
    for i in range(len(vec_a)):
        output = output + vec_a[i]
    return output

vector_sum_var = vector_sum(toes)
print(vector_sum_var)

def vector_average(vec_a):
    avg = np.average(vec_a)
    return avg


vector_sum_avg = vector_average(toes)
print(vector_sum_avg)

def dot_product(vec_a,vec_b):
    output = elementwise_multiplication(vec_a,vec_a)
    dot_prod = vector_sum(output)
    return dot_prod

dot_prod = dot_product(toes,wlrec)
print(dot_prod)

[5.525, 7.6000000000000005, 7.920000000000001, 8.1]
[9.15, 10.3, 10.700000000000001, 9.9]
36.9
9.225
341.51


In [41]:
## multiple inputs multiple outputs
 # toes % win # fans
weights = np.array([ [0.1, 0.1, -0.3],# hurt?
 [0.1, 0.2, 0.0], # win?
 [0.0, 1.3, 0.1] ])# sad?


def vect_mat_mul(input,weights):
    output = [0,0,0]
    for i in range(len(weights)):
        temp = input.dot(weights[i])
        output[i] = temp
    return output


def neural_network(input, weights):
    pred = vect_mat_mul(input,weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
pred

[ 0.1  0.1 -0.3]
---
[0.1 0.2 0. ]
---
[0.  1.3 0.1]
---


[0.5550000000000002, 0.9800000000000001, 0.9650000000000001]

In [47]:
## Network stacking


def vect_mat_mul(input,weights):
    output = [0,0,0]
    for i in range(len(weights)):
        temp = input.dot(weights[i])
        output[i] = temp
    return output


 # toes % win # fans
ih_wgt =np.array( [ [0.1, 0.2, -0.1], # hid[0]
 [-0.1,0.1, 0.9], # hid[1]
 [0.1, 0.4, 0.1] ]) # hid[2]


 #hid[0] hid[1] hid[2]
hp_wgt =np.array( [ [0.3, 1.1, -0.3], # hurt?
 [0.1, 0.2, 0.0], # win?
 [0.0, 1.3, 0.1] ]) # sad?

weights = np.array([ih_wgt, hp_wgt])

def neural_network(input, weights):
    hid = vect_mat_mul(input,weights[0])
    pred = vect_mat_mul(np.array(hid),weights[1]) 
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
pred

[0.21349999999999986, 0.14500000000000002, 0.5065]

In [48]:
## Numpy
import numpy as np
a = np.array([0,1,2,3]) 
b = np.array([4,5,6,7]) 
c = np.array([[0,1,2,3],
 [4,5,6,7]])
d = np.zeros((2,4)) 
e = np.random.rand(2,5)
print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.0314152  0.49153458 0.77185952 0.50915614 0.60650144]
 [0.65231725 0.5419614  0.31246863 0.80359036 0.9700735 ]]


In [50]:
print(a * 0.1) 
print("----")

print(c * 0.2) 
print("----")

print(a * b) 
print("----")

print(a * b * 0.2)
print("----")

print(a * c)
print("----")

print(a * e) 
print("----")


[0.  0.1 0.2 0.3]
----
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
----
[ 0  5 12 21]
----
[0.  1.  2.4 4.2]
----
[[ 0  1  4  9]
 [ 0  5 12 21]]
----


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [51]:
# [1,1,1,1]
# #1x4

# #4x3
# [[1,1,1,1],
# [1,1,1,1],
# [1,1,1,1]]

h = np.zeros((5,4)).T 
i = np.zeros((5,6)) 
j = h.dot(i)
print(j.shape)


(4, 6)
